README.md
Updated README file with project aims after discussions with Yan-Yin.
=> Changed project aims to reference local City of San Jose elections

README.md, package-lock.json
=> Updated readme

src/components/ballotInfo.js, src/components/measureInfo.js, src/components/measureInfo.module.css, src/components/sideNav.js, src/pages/electionInfo.js
Sorry about electionInfo.js - not sure why the formatting got so wonky.  I really only worked from line 149 to line 162.
=> Measure info page

.gitignore, scraper/scraper.py
Updates to the Scraper to work with changes to the SJC website
=> Scraper updates

README.md
Hope you do not mind the re-format. I think the links I found will live for a little while, though one never knows.
=> Break up long times and get rid of the link rot.

src/common/hamburgerIcon/index.js, src/components/ballotInfo.js, src/components/behindTheScenesItem.js, src/components/candidateItem.js, src/components/layout.js, src/components/mainPagePic.js, src/components/measureInfo.js, src/components/navbar.js, src/components/navbarItem.js, src/components/sideNav.js, src/components/snapshotItem.js, src/pages/electionInfo.js, src/pages/index.js
There are a number of console warnings related to accessibility. This PR addresses those so we have a better noise to signal ratio in the console.
=> Fix accessibilty console warnings

data_pipeline/data_api/README.md, data_pipeline/data_api/api/__init__.py, data_pipeline/data_api/api/candidate_api.py, data_pipeline/data_api/api/errors.py, data_pipeline/data_api/api/routes.py, data_pipeline/data_api/api/tests/unit/test_routes.py, data_pipeline/scraper/preproccessing.py, data_pipeline/scraper/scraper.py
Contains AC for July 9-July 23 2020
AC1: Create scraper endpoint to initialize the scraper constructor from localhost
AC2: Return fake data from an API endpoint (i.e. return 100000 from /total-contributions)
AC3: Return candidate info via POST request (i.e. total amount candidate rose)
=> #48 Fake Candidate Data and Scraper Endpoints

README.md, src/components/behindTheScenesItem.js, src/components/behindTheScenesItem.module.scss, src/components/layout.js, src/components/layout.module.scss, src/components/mainPagePic.module.scss, src/components/snapshotItem.js, src/components/snapshotItem.module.scss, src/pages/index.js, src/pages/index.module.scss
Minor UI updates to Index page and a couple components
=> Index word wrap

data_pipeline/scraper/dirmanager.py, data_pipeline/scraper/preproccessing.py, data_pipeline/scraper/scraper.py, data_pipeline/scraper/scraper_insert_candidates.py
only to get the master scraper running, inserting new columns for candidate/electiondate/ballot item still underway
=> scraper fixes

package.json, src/common/carousel/index.js, src/common/carousel/styles.module.scss, src/components/candidateItem.js, src/components/candidateItem.module.scss, src/components/candidateSection.js, src/components/mainPageSection.js, src/components/mainPageSection.module.scss, src/pages/index.js, src/styles/global.scss, yarn.lock
=> Index carousel

gatsby-node.js, src/templates/candidate.js, src/templates/candidate.module.scss
Leaving placeholders for the side nav and about section for now, and also leaving fake data for the charts.
=> Add GraphQL query to candidate page, add basic layout

src/common/button/styles.module.scss, src/components/barChart.module.scss, src/components/behindTheScenesItem.module.scss, src/components/candidateItem.module.scss, src/components/candidatesListItem.js, src/components/candidatesListItem.module.scss, src/components/layout.module.scss, src/components/mainPagePic.module.scss, src/components/mainPageSection.module.scss, src/components/menu.module.scss, src/components/navbar.module.scss, src/components/registerToVoteCard.module.scss, src/components/sideNav.module.scss, src/components/snapshotItem.module.scss, src/components/totalAmountItem.module.scss, src/pages/index.js, src/pages/index.module.scss, src/pages/registerToVote.module.scss, src/styles/global.scss, src/templates/candidate.module.scss, src/templates/candidates.js, src/templates/candidates.module.scss
Removed CSS making all divs, sections, uls, etc flex elements with flex-display column and fixed the discrepancies that my changes created.
=> Styling refactor

redis_api/redis_data/scraper_to_redis.py
Grouping candidates by committee name will allow the correct number of entries to be returned.
=> Group candidates by committee name

docker-compose.yml, redis_api/Dockerfile
Update Docker for redis_api.
Tested with docker-compose build api  and docker-compose up api
=> Update Docker for redis_api

gatsby-config.js, gatsby-node.js, src/data/measures/measure-g.json, src/data/measures/measure-h.json, src/templates/measure.js
It looks like my changes from #124 are already in master, and all we need to do to get my changes from #125 working is just to revert the last commit in master (which reverted the changes from #125). Testing this locally and it seems to work fine.
This reverts commit 1650bec6ad97f25f7cbbfe71cd46726b720ebd3b, reversing
changes made to 4077b37d4a48950a6bcecbc32e42fd4fcc10dca3.
=> Revert the last revert

data_pipeline/data_processing/aggregatedcsv2redis.py
fake data for now, to be deleted later
=> Put fake referendum data in elections population

data_pipeline/data_processing/aggregatedcsv2redis.py
1. Change dash inside ballot item into space for UI display
2. Change Candidate ID to remove space " " and replace it with underscore "_"
3. Add TotalFunding for each candidate in Candidates shape
4. FundingByGeo is now aggregated
'FundingByGeo': {'SJ': 45159.0, 'NonSJ': 46006.6, 'CA': 82430.6, 'NonCA': 8735.0}
5. Add TotalFunding in Committees in in Candidates shape
'Committees': [{'Name': 'Bay Area Municipal Elections Committee', 'TotalFunding': 600.0}, 
> The election shape in redis {'Elections': {'11/3/2020': {'Title': '2020 Election Cycle', 'Date': '11/3/2020', 'TotalContributions': 662734.9, 'OfficeElections': [{'Title': 'Councilmember District 4', 'CandidateIDs': ['Councilmember_District_4;David_Cohen;11/3/2020', 'Councilmember_District_4;Lan_Diep;11/3/2020'], 'TotalContributions': …
=> Refine candidate shape in redis

gatsby-node.js, src/data/candidates/david-cohen.json, src/data/candidates/devora-davis.json, src/data/candidates/jake-tonkel.json, src/data/candidates/lan-diep.json, src/templates/candidate.js, src/templates/candidates.js
Update the IDs so they link to the new candidate data. Also add Voter's Edge links and update the office title (seat) to 'Councilmember District x'
=> Update candidate json files

src/components/candidatesListItem.js, src/components/chartSection.js, src/components/sideNav.js, src/pages/index.js, src/templates/candidate.js
- Capitalization error with new blank profile image
- Fix a couple warnings about unused imports
=> Fix some errors and warnings

src/common/hamburgerIcon/index.js, src/components/barChart.js, src/components/barChart.module.scss, src/components/candidateItem.js, src/components/candidateItem.module.scss, src/components/faqitem.js, src/components/layout.js, src/components/layout.module.scss, src/components/mainPageSection.module.scss, src/components/navbar.js, src/components/navbar.module.scss, src/components/navbarItem.js, src/components/navbarItem.module.scss, src/components/sideNav.js, src/components/sideNav.module.scss, src/components/totalAmountItem.js, src/pages/404.js, src/pages/AboutUs.js, src/pages/faq.js, src/pages/findYourBallot.js, src/pages/getRegistered.js, src/pages/index.js, src/pages/registerToVote.js, src/styles/_colors.scss, src/styles/global.scss
Fixes react-axe warnings to improve page accessability
=> Fixes react axe issues

gatsby-node.js, src/components/candidatesListItem.js
Oops, I made #181 based on ui/schema-fixup instead of master, so the changes got merged to this branch instead. Let's merge these commits into master now.
=> Switch all funding totals in the UI to include LOAN (again)

src/pages/index.js
Updating copy based on @ychoy's suggestions in #184
=> Copy changes in live election snapshot

data_pipeline/data_processing/aggregatedcsv2redis.py, redis_api/api/routes.py
Added metadata population method and serve real metadata from routes
=> Add current and correct metadata

src/common/util/sorting.js, src/pages/index.js, src/templates/candidates.js
I added a sort function for the candidates list so that the candidates are displayed in descending order by the total amount of contributions. I also abstracted that function into a file in /utils so that I can reuse it on index.js.
=> Sorts candidates by desc amount of money

src/components/layout.js, src/components/layout.module.scss, src/components/menu.js, src/components/menu.module.scss, src/components/navbar.js, src/components/navbarItem.js, src/components/navbarItem.module.scss, src/pages/404.js
Removes the submenu from the candidates item and fixes keyboard nav issues on 404 page
=> Keyboard nav

src/components/candidateItem.module.scss
Fixes styling issue with candidate item pic's height
=> Fixes height of candidate item pic

gatsby-node.js, package.json, src/components/sideNav.module.scss, src/components/tableauViz.js, src/components/tableauViz.module.scss, src/templates/candidate.js, yarn.lock
Adds Tableau visualizations to Candidate pages and creates appropriate filters to select the candidate being viewed.
=> Tableau viz

src/components/navbar.module.scss
Fixes issue on mobile where you could scroll past the screen's horizontal limit
=> Changes top navbar to box sizing border box and increases width to 100%

src/components/mainPagePic.js, src/components/mainPagePic.module.scss, src/pages/index.js
MainPagePic component displaying weirdly on Chrome; image width distorted, fixed by adding width: 100%. flex-direction didn't seem to initialize correctly due to the use of `windowIsLarge` util.
=> Adds dimensions to html, adds width css for display on Chrome

README.md
Update readme with deployed version link so interested parties can see the state of the project.
- Describe what changes are being made
Currently no way to see state of project/current deployment unless asking project slack for a link to the deployed version.
- Describe why these changes are being made
Open access
- List the use cases and edge cases relevant to this PR
na
- Describe how errors will be handled. How will we know if this code breaks in production
na
- Describe any external libraries/dependencies added or removed in this PR
na
- Describe any security risks are there regarding this change
na
- Describe how you tested these changes
na
- Link to relevant external documentation
na
=> Update Readme with deployed version link

Dockerfile.dev, README.md, docker-compose.yml, entrypoint.sh
- Update README.md to use docker for local dev
- Frontend UI will automatically update on `http://localhost:8000` for quicker dev
=> Docker - Improvements for local dev

src/pages/aboutUs.js
Updates static data on About Us page about current members
- Describe what changes are being made
Updates member data for new co-leaders and active members
- Describe why these changes are being made
To keep the page up to date in case someone wants to know who is in charge
- List the use cases and edge cases relevant to this PR
- Describe how errors will be handled. How will we know if this code breaks in production
- Describe any external libraries/dependencies added or removed in this PR
- Describe any security risks are there regarding this change
- Describe how you tested these changes
- Link to relevant external documentation
--------------------------
-------------------------- …
=> Updates members

Dockerfile.dev
Fixing dockerfile as per https://github.com/nodejs/docker-node/issues/282
=> Fix dockerfile

data_pipeline/data_processing/requirements.txt, redis_api/requirements.txt
- Describe what changes are being made
- Describe why these changes are being made
- List the use cases and edge cases relevant to this PR
- Describe how errors will be handled. How will we know if this code breaks in production
- Describe any external libraries/dependencies added or removed in this PR
- Describe any security risks are there regarding this change
- Describe how you tested these changes
- Link to relevant external documentation
--------------------------
--------------------------
--------------------------
- PR = Pull Request
=> Rejson fix

src/pages/404.js
Made a small change to 404.js so it would work on my machine.
=> changed 404.js
