codeforsanjose/open-disclosure

src/components/menu.js, src/components/navbar.js, src/components/navbarItem.js
If we don't, then there is flickering when a user adjusts the screen size past the responsive breakpoint.
Gif:
=> Take window size into consideration when rendering menu

src/components/barChart.js, src/components/barChart.module.scss, src/pages/candidate.js, src/pages/candidate.module.scss
Creating a <BarChart /> component that renders the contributions/expenditures charts from the candidate and measure pages. Mocks: https://www.figma.com/file/GmfndRmQChBeoklOkmi0FC/Open-Disclosure?node-id=1433%3A1563
Also stubbed out a `/candidate` page that just renders three charts with mock data, for now. It needs an actual layout, and to be hooked up to real data.
The one UX issue that I'm still not super happy with is how the border radius on the bar looks when the value is really small - it still applies the same border radius, which makes it look... squished.
I think my preference would be to remove or change the border radius when width < height, but I'm not sure the best way to do that (is this something I can do in CSS?). From the mocks it's not totally clear how this should be …
=> Create bar chart component

src/components/barChart.module.scss, src/components/sectionHeader.js, src/components/sectionHeader.module.scss, src/components/totalAmountItem.js, src/components/totalAmountItem.module.scss, src/pages/candidate.js, src/pages/candidate.module.scss
Creating a couple of components to be used in the Candidate page and adding them to the stubbed-out page. This PR includes a component to render the section header (h3 + divider line) as well as the formatted dollar value + label for contribution/expenditure totals.
The TotalAmountItem component needs to look slightly different depending on where it's rendered. The easiest way I found to do that was just to export a second component (TotalAmountPanelItem) from the same file, so it can share the logic and CSS with the non-panel version that appears above all the charts. I guess I could also use a prop for this instead - not sure which makes more sense.
=> Create components for Candidate page

src/common/button/styles.module.scss, src/common/hamburgerIcon/styles.module.scss, src/components/barChart.module.scss, src/components/behindTheScenesItem.module.scss, src/components/candidateItem.module.scss, src/components/faqItem.module.scss, src/components/landingPageHero.module.scss, src/components/layout.module.scss, src/components/logo.module.scss, src/components/mainPageSection.module.scss, src/components/navbar.module.scss, src/components/navbarItem.module.scss, src/components/registerToVoteCard.module.scss, src/components/sectionHeader.module.scss, src/components/snapshotItem.module.scss, src/pages/index.module.scss, src/styles/_colors.scss, src/styles/global.scss
Moving all color variable definitions to a single .scss file and using `@import` to use those variables everywhere else. I (mostly) used [the palette in Figma](https://www.figma.com/file/GmfndRmQChBeoklOkmi0FC/Open-Disclosure?node-id=2029%3A0), but there were a few things missing that I left in and made up a name for.
Also cleaning up some of the places where we still use hex values in our .scss files - I mostly just used the variable with the same hex value, except for the places where 'black' or #000 was used, which I swapped for $primaryBlack. I left the .css files alone.
=> Color variables

gatsby-config.js, yarn.lock
When I hooked up the candidates page to the API I hardcoded the plugin to use `localhost:5000`, but that's clearly not always going to work. Coco ran into an error when they were running the Flask server somewhere else, which caused a Gatsby compilation error. This PR checks an environment variable for the API server before falling back to localhost.
In the future we should probably make sure that it fails gracefully if the API isn't available (I thought the plugin should already do that, but it seems like it doesn't?) and only use localhost in dev. But this should help fix the issue for now.
=> Use an environment variable for the flask server

plugins/source-api-plugin/gatsby-node.js, src/pages/index.js
I added another fetch request to our new Gatsby source plugin, so it now fetches from both `/candidates` and `/elections` and creates GraphQL nodes for the data it gets back. Also, I added an export for the GraphQL query to index.js, so this data is now available on this page through `this.props.data`. To use this data in another page, just add an export for your query:
```
export const query = graphql` ... `
```
and then Gatsby will magically hook it up so your React component receives a prop called `data` with the result.
Both of these queries, along with the mock data for them, are just hardcoded in this plugin for now. I could refactor it so that the plugin accepts the API endpoint as a param, and we just create multiple instances of the plugin to query multiple endpoints. But I'm …
=> Fetch data from /elections endpoint, add GraphQL queries to index.js

gatsby-config.js, plugins/source-api-plugin/gatsby-node.js, src/pages/candidates.js, src/pages/index.js
Right now the Candidates page lists all the candidates it gets back from the /candidates endpoint, regardless of which election they're participating in. In order to only show candidates for the current election, and to be able to show them in the context of the actual race they're running in, it'll be better if we can get the candidate data through the /elections endpoint instead. However, that endpoint currently only give us the names of the candidates: ['Lindsay Lohan', 'Jake John'], while the /candidates endpoint provides more data (elections, committees, etc.).
This PR links the data we get from the `/candidates` endpoint with the data we get from `/elections` in GraphQL by setting up a foreign key relationship between the respective GraphQL nodes. As a result of this change, you can …
=> Link Election and Candidate GraphQL nodes

src/templates/candidate.js
error during build of front-end container due to png image import name different from actual file name
`Can't resolve '../../static/images/votersedge.png' in '/usr/src/app/open-disclosure/src/templates'
If you're trying to use a package make sure that '../../static/images/votersedge.png' is installed. If you're trying to use a local file make sure that the path is correct.
File: src/templates/candidate.js`
=> resolving container build issue for frontend

gatsby-config.js, plugins/source-api-plugin/gatsby-node.js
In order to use our plugin to create a slug for OfficeElections, it needs to be an actual GraphQL node. Making it a node by calling createNode, and linking it to the Election node in the schema.
=> Create GraphQL node for OfficeElection type and make a slug for it

data_pipeline/data_api/api/routes.py, redis_api/api/__init__.py
One of these is because redis_routes.py was renamed to routes.py. For the other, I'm not sure if this is currently working for anyone else? But it's complaining because redis isn't imported.
=> Fix a couple of Python errors I'm hitting running flask app

gatsby-node.js, plugins/source-api-plugin/gatsby-node.js, src/data/candidates/david-cohen.json, src/data/candidates/devora-davis.json, src/data/candidates/jake-tonkel.json, src/data/candidates/lan-diep.json, src/pages/index.js, src/templates/candidate.js
In this PR:
- Update the mock data for Candidates to match what's now being returned from the API. The biggest change is lifting the 'Committees' field to be directly exposed on the Candidate node (now you can do candidate.Committees instead of candidate.elections.forEach(election => election.Committees)
- Move the GraphQL schema customization out of the plugin and into our main gatsby-node.js, so that I can link from the JSON node to the api node. Now you can do: candidateJson.apiData.Committees
- Update the JSON files to add the ID field and standardize the names, since those are still used for the page slugs (will update that later)
=> Update candidate schema

gatsby-config.js, gatsby-node.js, src/data/measures/measure-g.json, src/data/measures/measure-h.json, src/templates/measure.js
Initially I was going to sync the referendums schema from the API, but it sounds like none of the measures actually have any funding data. So instead of hooking this up to the API, let's just create JSON files for each measure in the election (there are only two, it seems) and use those to create and render the measure pages.
It looks like the measure pages PR isn't merged yet, so I'm just creating a placeholder `measure.js` in /templates for now.
=> Create measure pages using JSON data

gatsby-node.js, src/components/candidatesListItem.js, src/templates/candidate.js, src/templates/candidates.js
Making some changes to how we create pages to make it easier to include the election date and office title in the path of the candidate page URL. So instead of being:
/candidate/lan-diep
it will now be:
/2020-11-03/candidate/district-4-representative/lan-diep
Also, making some changes to how we access candidate data in GraphQL. We can now link both ways from JSON data <-> API data (before it was just JSON -> API). On the candidate page, instead of fetching the JSON node and linking to the API node, I'm doing the reverse. This lines up a little better with what we're doing in the rest of the site. This doesn't really have any effect on anything, I'm just doing it to be more consistent.
=> Include election date + office title in candidate page path

gatsby-node.js
This PR updates the frontend to handle the API changes made in #134. We'll need to merge it once that PR is merged to be able to use the API again.
The main change here is just flattening the data returned from elections, so instead of returning an array of Election objects, it now returns a key-value map where the key is the election date ('11/3/2020') and the value is the election object. This makes it easier for us to just fetch data for a specific election instead of iterating over all of them, or grabbing the first one.
=> Update client-side schema with API changes from Redis

gatsby-node.js, src/templates/candidates.js
Right now we query allElections on the candidates page and iterate over all the office elections and candidates, which means that we show all four candidates regardless of which race is selected. This PR passes in the officeElectionID to the candidates page and uses that to query only the specific officeElection.
=> Query specific office election from candidates pages

src/common/util/formatters.js, src/components/barChart.js, src/components/candidateItem.js, src/components/candidateItem.module.scss, src/components/candidatesListItem.js, src/components/totalAmountItem.js, src/pages/index.js
- Hook them up to the correct funding field from the API (now that it exists)
- With four of them + real (large) funding numbers, they don't really fit on the screen anymore. Switching them to use shorter currency notation ('$100K' instead of '$100,000')
- Hooking them up to the candidate pages so you can click on them
=> Update the candidate cards on the index page

src/data/candidates/david-cohen.json, src/data/candidates/devora-davis.json, src/data/candidates/jake-tonkel.json, src/data/candidates/lan-diep.json
Top priority; without the updated IDs the app can't link the jsonNode field to the candidate.
=> Updates IDs for Candidate JSON

src/templates/candidate.js
This chart now has 3 rows: % raised from within SJ, % raised from *the rest of* California (not including SJ), and % raised out-of-state. I excluded SJ from the California row because that seemed to make the most sense with the mocks (otherwise the values add up to >100%). But I think the UX could be a little clearer - should we change the label to 'the rest of California' or something like that?
=> Update funding by region to include SJ

src/common/util/codes.js, src/components/barChart.js, src/templates/candidate.js
Added a tooltip for each contributor and expenditure code to provide more information. This currently uses the HTML title attribute so it's not accessible or mobile-friendly :( 
Also, show all expenditure codes with data instead of just the top 4.
=> Add tooltips for expenditure/contributor codes, show all expenditure types

src/common/hooks/useWindowIsLarge.js
Apparently gatsby build does server-side rendering, and window doesn't exist then? Anyway, this is only used for the default value of useWindowIsLarge
=> Check if window exists

src/common/hooks/useWindowIsLarge.js, src/components/sideNav.js, src/templates/candidate.js, src/templates/candidates.js, src/templates/referendum.js
Change referendum.js to use the passed-in id to query only for a specific measure, and pass in selectedTitle to sideNav so it doesn't need to get it from window.location.href. After these changes, `gatsby build` should work.
=> Remove window usage from sideNav.js

src/components/navbar.js
We were seeing an issue where scrolling wouldn't get re-enabled when you clicked on a link in the nav bar menu to navigate to a new page - it would only re-enable scrolling when you explicitly closed the menu. It looks like `window.onscroll` was being reset properly, but `document.body.style.overflow` was only being updated in the menu's onClick. This PR simplifies the logic a bit so that we handle all the menu open/close behavior in the same useEffect callback.
I'm also returning enableScroll() from the useEffect just to make sure that scrolling is re-enabled, in case you navigate to a page that doesn't have the navbar on it somehow.
=> Fix issue where scroll doesn't get re-enabled from navbar

src/components/bar.js, src/components/barChart.js, src/templates/candidate.js
Misc. UI fixes for candidate page:
- Un-linkify committees since they don't go anywhere
- Remove 'See All Contributions' link for now
- Add a minimum sliver in the bar charts with small values > 0
- Update the Committees header text to indicate support vs. candidate owned
- Add SJ to the funding by geo breakdown
=> Clean up candidate page

gatsby-node.js
There are a few places where we use the TotalFunding field on candidate (which includes RCPT + LOAN) instead of TotalContributions (only RCPT). Since all of the candidate funding breakdowns and the office election TotalFunding field both only use RCPT, let's switch everything over to only using RCPT for now. Once the API has been updated to include LOAN, I'll update these fields so everything includes LOAN.
=> Overwrite TotalFunding with TotalRCPT (for now)

gatsby-node.js
Still using the env variable GATSBY_API_HOST in case we need to override it. But hopefully this means we don't need to set it in the build scripts if we just want to use the deployed version of the API.
=> Default to deployed API for prod environment

src/pages/faq.js
It looks like lint errors are now causing gatsby to fail to build the JS bundle with `gatsby develop`. Cleaning up a few of the errors in faq.js:
- Giving names to functions that are used as React components
- Getting rid of ' and replacing it with ’ (it was complaining about using un-escaped single quote, replaced it with smart quotes because I think it looks better here anyway - San José's vs. San José’s)
- Remove unused function
=> Fix lint errors in faq.js

gatsby-node.js, src/components/candidatesListItem.js
Now that @geleazar1000111 has made the change on the backend so that the breakdowns include LOAN, we can remove our overrides and include LOAN in everything in the UI.
Also fix something I broke on the candidates page (I changed the props of the Bar component without fixing this callsite).
=> Switch all funding totals in the UI to include LOAN 

src/pages/index.js
Calculating this by adding up all the SJ funding info from the candidates. We don't have funding data for measures yet, but we should add that once we do.
=> Replace 'XXX' on home page with num calculated from candidate data

gatsby-node.js, src/pages/index.js
DateProcessed is currently a required field in our GraphQL schema, so if the backend doesn't provide it you get build errors on the frontend. This PR makes it optional, and only uses it in index.js if provided.
Here's what it looks like without the date:
=> Make DateProcessed optional

src/components/mainPageSection.module.scss
Removes some padding from the mainPageSection innerContainer that would stretch the page past its 1440px limit when the window's width was changed.
=> Removes padding from side of mainPageSection

src/components/candidatesListItem.js, src/templates/candidates.js
Gets the TotalContributions for most prolific earner (takes the 0th item's TotalContributions from the array sorted by highest to lowest TC) and uses that as the denominator rather than the TC of the entire election.
#212
=> Changes denominator of bar graph

src/components/layout.js, src/pages/index.js
Puts a div around the `props.children` of layout.js so it creates room between header and footer, adds a `'T'` in between date and time values of `ProcessedDate` on index.js as required for use in Safari
=> Fixes layout and Date issues on Safari

data_pipeline/scraper/scraper.py
Bug fix
- Describe what changes are being made
Modified scraper.py such that it renames the downloaded transactionExportGrid.xls file into transactionExportGrid.xls(1) or transactionExportGrid.xls(2) and so on. 
- Describe why these changes are being made
To avoid overwriting downloaded files in the headless mode
- List the use cases and edge cases relevant to this PR
- Describe how errors will be handled. How will we know if this code breaks in production
- Describe any external libraries/dependencies added or removed in this PR
None
- Describe any security risks are there regarding this change
- Describe how you tested these changes
- Link to relevant external documentation …
=> Fixed overwriting downloaded files in headless mode
